### PR TITLE
Electron

### PR DESCRIPTION
**Pull request by kristianmandrup**
Please review this much improved CLI :)

-  refactored wrapper
- added electron wrapper
- made init more flexible and powerful
- updated README :)

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thank you so much for your hard work! I'll do some polishing and release the new CLI in a few days.

**Comment by kristianmandrup** [comment]
Awesome :)

**Comment by IniZio** [comment]
wow so quasar will be getting mobile and electron support?

**Comment by rstoenescu** [comment]
Yep.

**Pull request merged**
